name: CYOAP release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - run: 7z a build/windows/cyoap_windows_${{ steps.get_version.outputs.version-without-v }}.zip ./build/windows/runner/Release/*

      - name: base64-to-file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'key.properties'
          fileDir: './android/'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - run: flutter build apk --release
      - run: Rename-Item "build/app/outputs/flutter-apk/app-release.apk" "cyoap_android_${{ steps.get_version.outputs.version-without-v }}.apk"

      - name: Build web distribute
        run: flutter build web --web-renderer html --release
      - run: rmdir /s /q ./build/web/canvaskit
      - run: del /f /q /a ./build/web/.last_build_id
      - run: del /f /q /a ./build/web/assets/NOTICES
      - run: 7z a build/web/distribute_${{ steps.get_version.outputs.version-without-v }}.zip ./build/web/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_ACTION }}
          files: |
            build/windows/cyoap_windows_${{ steps.get_version.outputs.version-without-v }}.zip
            build/app/outputs/flutter-apk/cyoap_android_${{ steps.get_version.outputs.version-without-v }}.apk
            build/web/distribute_${{ steps.get_version.outputs.version-without-v }}.zip
            

      - name: Remove web folder
        run: rmdir /s /q build

      - run: flutter build web --web-renderer canvaskit --release --base-href=/FlutterCyoap/

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web