name: CYOAP release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - run: 7z a build/windows/cyoap_windows_${{ steps.get_version.outputs.version-without-v }}.zip ./build/windows/runner/Release/*

      - name: base64-to-file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'key.properties'
          fileDir: './android/'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - run: flutter build apk --release
      - run: Rename-Item "build/app/outputs/flutter-apk/app-release.apk" "cyoap_android_${{ steps.get_version.outputs.version-without-v }}.apk"

      - name: Build web distribute
        run: flutter build web --web-renderer html --release --dart-define="isDistributed"=true
      - run: Remove-Item ./build/web/canvaskit -Recurse | Remove-Item
      - run: Remove-Item ./build/web/.last_build_id
      - run: Remove-Item ./build/web/assets/NOTICES
      - run: Remove-Item ./build/web/save_web.js
      - run: Remove-Item ./build/web/jszip.js
      - run: Remove-Item ./build/web/worker.js
      - run: Remove-Item ./build/web/assets/packages/flutter_inappwebview -Recurse | Remove-Item
      - run: Remove-Item ./build/web/assets/packages/youtube_player_flutter -Recurse | Remove-Item
      - run: Copy ./web_distribute_only/worker.js ./build/web

      - run: get-content ./build/web/index.html | select-string -pattern '.*(save_web.js|jszip.js).*' -notmatch | Out-File ./build/web/index_replaced.html
      - run: Remove-Item ./build/web/index.html
      - run: Rename-Item ./build/web/index_replaced.html index.html

      - run: get-content ./build/web/flutter_service_worker.js | select-string -pattern '.*(Notice|save_web.js|jszip.js|canvaskit).*' -notmatch | Out-File ./build/web/flutter_service_worker_replaced.js
      - run: Remove-Item ./build/web/flutter_service_worker.js
      - run: Rename-Item ./build/web/flutter_service_worker_replaced.js flutter_service_worker.js

      - run: 7z a build/web/distribute_${{ steps.get_version.outputs.version-without-v }}.zip ./build/web/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/windows/cyoap_windows_${{ steps.get_version.outputs.version-without-v }}.zip
            build/app/outputs/flutter-apk/cyoap_android_${{ steps.get_version.outputs.version-without-v }}.apk
            build/web/distribute_${{ steps.get_version.outputs.version-without-v }}.zip

      - name: Remove web folder
        run: Remove-Item ./build/web -Recurse | Remove-Item

      - run: flutter build web --web-renderer canvaskit --release --base-href=/FlutterCyoap/

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web