name: CYOAP release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build/windows/build.zip build/windows/runner/Release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_ACTION }}
          files: |
            build/windows/build.zip